# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.14.181554'

RELEASE_GIT_HEAD = '42f50ba2f68604e624f9e35add8d5f368f527786'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'jkruse/yt-dlp'

ORIGIN = 'jkruse/yt-dlp'

_pkg_version = '2025.03.14.181554'
